#!/bin/sh
state=`$HOME/.xmonad/get-battery`
bat=`echo $state | cut -c 2-3 | sed 's/%//'`
batall=`echo $state | cut -c 2-4`

if [ "$bat" -eq "100" ]; then
  echo "^fg(#00aa4a)"
elif [ "$bat" -lt "16" ]; then
  echo "^fg(#cc0000)"
elif [ "$bat" -gt "60" ]; then
  echo "^fg(#00aa4a)"
else
  echo "^fg()"
fi

